server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${DBMS_URL}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
#       Hibernate sẽ tự động tạo bảng dựa trên Entity (nếu chưa có) và cập nhật schema nếu thay đổi.
      ddl-auto: update
#       Hiển thị câu lệnh SQL trên console.
    show-sql: true
jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 12000 #seconds
  refreshable-duration: 36000 #seconds
