server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${DBMS_URL}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      #       Hibernate sẽ tự động tạo bảng dựa trên Entity (nếu chưa có) và cập nhật schema nếu thay đổi.
      ddl-auto: update
    #       Hiển thị câu lệnh SQL trên console.
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 1200000 #seconds
  refreshable-duration: 3600000 #seconds
cloudinary:
  cloudName: ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
momo:
  partnerCode: MOMOIBXY20250219_TEST
  accessKey: aPuvoDokFzV6Izbg
  secretKey: 9C8GOJ3F4y8k3OuGK0xg0cCwnIvc1sTo
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirectUrl: http://localhost:6001
  ipnUrl: http://localhost:8080/api/order/payment/callback
  requestType: captureWallet
  urlCheckTransaction: https://test-payment.momo.vn/v2/gateway/api/query
